<?php

/**
 * @file
 * Contains customization.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function fancy_local_tasks_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the customization module.
    case 'help.page.fancy_local_tasks':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Fancy local tasks module') . '</p>';
      return $output;

    default:
      return '';
  }
}

/**
 * Implements hook__preprocess_page().
 */
function fancy_local_tasks_preprocess_page(&$variables) {
  if ($variables['logged_in'] && !\Drupal::service('router.admin_context')->isAdminRoute()) {
    $variables['#attached']['library'][] = 'fancy_local_tasks/fancy-local-tasks';
  }
}

/**
 * Implements hook_theme_registry_alter().
 */
function fancy_local_tasks_theme_registry_alter(&$theme_registry) {

  if (!\Drupal::service('router.admin_context')->isAdminRoute()) {
    $theme_registry['menu_local_tasks']['path'] = drupal_get_path('module', 'fancy_local_tasks') . '/templates';
  }
}
